### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by CarlOlsson** [CarlOlsson/matulog#1]
- [x] Fix colors for plotting the variables, so they don't change color when new variables are added or removed.
- [ ] Create a re-sampled version of the log and add a topic calculated in pre-processing with interesting fields, such as magnetometer norm, euler angles etc.
- [ ] Save entire logfile to workspace button
- [ ] Save selected part of logfile to workspace button
- [ ] Calculate mean of selected part of displayed variables button
- [ ] Calculate variance of selected part of displayed variables button
- [ ] Calculate fft of selected part of displayed variable button
- [ ] Convert the .ulg file to a .mat without going via .csv files (for speed)
- [x] edit the cursor function to display the all variable names and the corresponding value
- [x] Implement button for exporting the plot to image file
- [ ] Implement a button to save plot to clip board. E.g for easy uploading to github
- [ ] Implement an option in axes context menu to rescale all variables to [-1 1]
- [x] Constant list of displayed variables when changing logfile for easy comparison of data
- [ ] Implement user specified "presets" of a list of variables to display
- [ ] Implement an easy to maintain interface for additional functions
- [ ] Implement trajectory analysis (2D/3D plot of flight path)
- [x] Fix the x axis such that it displays all topics from start to end
- [ ] Implement "view parameters" and "view messages" buttons
- [ ] Implement vertical lines displaying VTOL transition
- [ ] Make the zoom not change when adding/removing variables to plot
- [ ] Display NaNs
- [ ] Add button to convert all ulg files to mat files in folder
- [x] add button to redo preprocessing
- [ ] Implement button to move legend
- [ ] In preprocessing, create a topic for the estimator flag bitfields
- [ ] When starting the gui, add the folder to the path
